apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
  namespace: django-tutorial
data:
  db-password: ZGphbmdvX3Bhc3N3b3Jk
  db-root-password: cm9vdF9wYXNzd29yZA==
  django-superuser-password: YWRtaW4xMjM=
