apiVersion: v1
kind: Service
metadata:
  name: django-service
  namespace: django-tutorial
  labels:
    app: django-tutorial
    tier: frontend
spec:
  type: NodePort
  selector:
    app: django-tutorial
    tier: frontend
  ports:
  - port: 8000
    targetPort: http-server
