apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
  namespace: django-tutorial
data:
  DB_HOST: "mariadb-service"
  DB_NAME: "tutorial"
  DB_USER: "django_user"
  DB_PORT: "3306"
  DJANGO_SUPERUSER_USERNAME: "admin"
  DJANGO_SUPERUSER_EMAIL: "admin@example.com"
  CSRF_TRUSTED_ORIGIN: "http://django-tutorial.local"
